# Generated by Django 4.0.6 on 2022-12-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='att_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
