# Generated by Django 4.0.6 on 2022-12-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cartorderitems_att_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='color',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='delivery_charge',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='size',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
